name: Build and push Docker image

on:
  push:
    branches:
      - demonstrator
  pull_request:
    branches:

jobs:
  build:
    name: "Build and push Docker image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: >
          docker build
          --tag c4dt/garfield-pytorch-demo:latest
          --file pytorch_impl/Dockerfile
          .

      - name: Push
        run: >
          docker login
          --username ${{ secrets.DOCKER_USERNAME }}
          --password ${{ secrets.DOCKER_PASSWORD }} &&
          docker push c4dt/garfield-pytorch-demo:latest
