name: Build and push Docker image, deploy on target

on:
  push:
    branches:
      - demonstrator
  pull_request:
    branches:
      - demonstrator

jobs:
  build:
    name: "Build and push Docker image, deploy on c4dtsrv1"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: >
          docker build
          --tag c4dt/garfield-pytorch-demo:latest
          --file pytorch_impl/Dockerfile
          .

      - name: Push
        if: github.event_name == 'push'
        run: >
          docker login
          --username ${{ secrets.DOCKER_USERNAME }}
          --password ${{ secrets.DOCKER_PASSWORD }} &&
          docker push c4dt/garfield-pytorch-demo:latest

      - name: Deploy
        if: github.event_name == 'push'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H c4dtsrv1.epfl.ch > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          cat scripts/deploy.sh | ssh -i ssh-key garfield@c4dtsrv1.epfl.ch
